from enum import Enum


class RiskType(str, Enum):
    FAILED_PAYMENT = "FAILED_PAYMENT"
    CHECKOUT_ABANDONMENT = "CHECKOUT_ABANDONMENT"
    SUBSCRIPTION_FAILURE = "SUBSCRIPTION_FAILURE"
    OVERDUE_RECEIVABLE = "OVERDUE_RECEIVABLE"


class CaseStatus(str, Enum):
    OPEN = "OPEN"
    DIAGNOSING = "DIAGNOSING"
    READY_FOR_ACTION = "READY_FOR_ACTION"
    PENDING_APPROVAL = "PENDING_APPROVAL"
    EXECUTING = "EXECUTING"
    RECOVERED = "RECOVERED"
    FAILED = "FAILED"
    ESCALATED = "ESCALATED"
    STOPPED = "STOPPED"
    EXPIRED = "EXPIRED"


class InterventionType(str, Enum):
    RETRY = "RETRY"
    PAYMENT_LINK = "PAYMENT_LINK"
    EMAIL = "EMAIL"
    SMS = "SMS"
    WHATSAPP = "WHATSAPP"
    SUBSCRIPTION_RETRY = "SUBSCRIPTION_RETRY"
    HUMAN_ESCALATION = "HUMAN_ESCALATION"
    STOP = "STOP"


class RootCauseCategory(str, Enum):
    TEMPORARY_PAYMENT_FAILURE = "TEMPORARY_PAYMENT_FAILURE"
    CUSTOMER_PAYMENT_ISSUE = "CUSTOMER_PAYMENT_ISSUE"
    REPEATED_PAYMENT_FAILURE = "REPEATED_PAYMENT_FAILURE"
    CHECKOUT_ABANDONMENT = "CHECKOUT_ABANDONMENT"
    SUBSCRIPTION_FAILURE = "SUBSCRIPTION_FAILURE"
    OVERDUE_RECEIVABLE = "OVERDUE_RECEIVABLE"
    UNKNOWN = "UNKNOWN"


class StoppingReason(str, Enum):
    MAX_RETRY_ATTEMPTS = "MAX_RETRY_ATTEMPTS"
    MAX_CONTACT_ATTEMPTS = "MAX_CONTACT_ATTEMPTS"
    CUSTOMER_OPT_OUT = "CUSTOMER_OPT_OUT"
    CASE_EXPIRED = "CASE_EXPIRED"
    COOLDOWN_ACTIVE = "COOLDOWN_ACTIVE"
    POLICY_BLOCK = "POLICY_BLOCK"
    REPEATED_GATEWAY_REJECTS = "REPEATED_GATEWAY_REJECTS"
    HUMAN_ESCALATION_REQUIRED = "HUMAN_ESCALATION_REQUIRED"
    REVENUE_RECOVERED = "REVENUE_RECOVERED"
    MERCHANT_REJECTED = "MERCHANT_REJECTED"
    HARD_FAILURE_PERMANENT = "HARD_FAILURE_PERMANENT"


class AuditEventType(str, Enum):
    PAYMENT_FAILED = "PAYMENT_FAILED"
    REVENUE_RISK_DETECTED = "REVENUE_RISK_DETECTED"
    CUSTOMER_CONTEXT_RETRIEVED = "CUSTOMER_CONTEXT_RETRIEVED"
    DIAGNOSIS_COMPLETED = "DIAGNOSIS_COMPLETED"
    RECOVERABILITY_SCORED = "RECOVERABILITY_SCORED"
    ACTION_PROPOSED = "ACTION_PROPOSED"
    POLICY_CHECK = "POLICY_CHECK"
    ACTION_APPROVED = "ACTION_APPROVED"
    ACTION_REJECTED = "ACTION_REJECTED"
    ACTION_BLOCKED = "ACTION_BLOCKED"
    ACTION_EXECUTED = "ACTION_EXECUTED"
    EXECUTION_FAILED = "EXECUTION_FAILED"
    PAYMENT_LINK_CREATED = "PAYMENT_LINK_CREATED"
    PAYMENT_RECEIVED = "PAYMENT_RECEIVED"
    PAYMENT_VERIFIED = "PAYMENT_VERIFIED"
    REVENUE_RECOVERED = "REVENUE_RECOVERED"
    HUMAN_ESCALATION = "HUMAN_ESCALATION"
    CASE_STOPPED = "CASE_STOPPED"
    WEBHOOK_RECEIVED = "WEBHOOK_RECEIVED"


class ActorType(str, Enum):
    SYSTEM = "SYSTEM"
    AI_AGENT = "AI_AGENT"
    POLICY_ENGINE = "POLICY_ENGINE"
    MERCHANT_USER = "MERCHANT_USER"
    CUSTOMER = "CUSTOMER"
    PAYMENT_GATEWAY = "PAYMENT_GATEWAY"


class PaymentStatus(str, Enum):
    CREATED = "CREATED"
    AUTHORIZED = "AUTHORIZED"
    CAPTURED = "CAPTURED"
    FAILED = "FAILED"
    REFUNDED = "REFUNDED"


class NotificationChannel(str, Enum):
    EMAIL = "EMAIL"
    SMS = "SMS"
    WHATSAPP = "WHATSAPP"
